# Configuration used by latexindent.pl
defaultIndent: "  "

# codeblock is defined by sjtubeamer for code typesetting.
# codeblockminted is defined by minted plugin.
verbatimEnvironments:
  codeblock: 1
  codeblockminted: 1

# In case that the indent for the command.
verbatimCommands:
  url: 1
  link: 1
  href: 1

# Apply to -m option
# Chinese docs are restricted to 50 characters first.
modifyLineBreaks:
  textWrapOptions:
    columns: 100

# Don't generate too many backups.
onlyOneBackUp: 1

# Convert CRLF to LF.
dos2unixlinebreaks: 1
